[package]
# [strings]
name = 'nature-elsewhere'
description = 'An isometric adventure in an idealized state of nature.'
version = '0.0.0'
keywords = ['game', 'webgl', 'isometric', 'adventure', 'pixel-art', 'aseprite']
categories = ['games']
documentation = 'https://github.com/oddoid/nature-elsewhere'
homepage = 'https://github.com/oddoid/nature-elsewhere'
repository = 'https://github.com/oddoid/nature-elsewhere'
readme = 'readme.md'
license = 'GPL-3.0-only AND CC-BY-SA-4.0'
edition = '2018'
authors = ['oddoid']

[badges]
is-it-maintained-issue-resolution = { repository = 'https://github.com/oddoid/nature-elsewhere' }
is-it-maintained-open-issues = { repository = 'https://github.com/oddoid/nature-elsewhere' }
maintenance = { status = 'experimental' }

[lib]
crate-type = ['cdylib']

[profile.release]
opt-level = 'z' # Optimize for size.
lto = true

[dependencies]
image = {version = '0', default-features = false, features = ['png_codec']}
num-traits = '0'
serde = '1'
serde_derive = '1'
serde_json = '1'
wasm-bindgen = '0'
web-sys = {version = '0', features = [
  'AngleInstancedArrays', 'console', 'Document', 'Element', 'HtmlCanvasElement',
  'HtmlElement', 'HtmlImageElement', 'WebGlActiveInfo', 'WebGlBuffer',
  'WebGlProgram', 'WebGlRenderingContext', 'WebGlShader', 'WebGlTexture',
  'WebGlUniformLocation', 'Window'
]}

[target.'cfg(debug_assertions)'.dependencies]
console_error_panic_hook = '0'
