max_width = 80
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Max"
use_try_shorthand = true
use_field_init_shorthand = true
print_misformatted_file_names = true
# condense_wildcard_suffixes = true
# fn_single_line = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_strings = true
# inline_attribute_width = 80
# match_arm_blocks = false
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# trailing_comma = 'Never'
# trailing_semicolon = false
# version = 'Two'
# where_single_line = true
